/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */
package analizadormoderacion;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GROSERIA = 5;
  /** RegularExpression Id. */
  int ACEPTADO = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "<GROSERIA>",
    "<ACEPTADO>",
  };

}
